---
.travis.yml:
  forge_password: "Me3LMTfW68yLhQZd99QNYLk8nur8dKvMIW1ldsQ2zUjJrclRnTkEnmXRpQ2XBCoZ0XsQFxJHnY0FQx8NFSYRNbaMKssVRiWdueW1NGZvsgbLPNwiAj07O/cCSDwGP2gOuHZPA75tOFU7cWzGyyNSoKr2ZCL+xlxzjv9/v/gHMNU="
